name = "supermemory"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"


kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "6df98c892b3744ccb0c631d9f60d6697" },
	{ binding = "RECOMMENDATIONS", id = "83bc7055226c4657948141c2ff9a5425" }
]

env.production.kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "6df98c892b3744ccb0c631d9f60d6697" },
	{ binding = "RECOMMENDATIONS", id = "83bc7055226c4657948141c2ff9a5425" }
]

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "dev-r2-anycontext"

[[d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "231def91-f7e8-4788-9e9f-80cb0b135a7c"


[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-prod"
database_id = "021f8266-361a-4dae-9264-b35a765e4dfc"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "231def91-f7e8-4788-9e9f-80cb0b135a7c"

[env.production.ai]
binding = "AI"