name = "supermemory"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "cf4603d565574066be9f8e42e507c698" },
	{ binding = "RECOMMENDATIONS", id = "88377b2d62c949b186bd194e31a6fb3b" },
]

env.production.kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "cf4603d565574066be9f8e42e507c698" },
	{ binding = "RECOMMENDATIONS", id = "88377b2d62c949b186bd194e31a6fb3b" },
]

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "supermemory-r2"

[[d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "4588e7be-42a8-41c9-b134-6b3b6a32fa3a"


[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-prod"
database_id = "a17babca-e3fc-448c-bd89-dc901a06e358"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "4588e7be-42a8-41c9-b134-6b3b6a32fa3a"

[env.production.ai]
binding = "AI"
